export const StatusLabel = {
  // Quality gate
  PASS: 'PASS',
  FAIL: 'FAIL',
  NOT_EVALUATED: 'NOT_EVALUATED',
  // Routing
  CANDIDATE_READY: 'CANDIDATE_READY',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  SIGNAL_INVALID: 'SIGNAL_INVALID',
  INPUT_LOST: 'INPUT_LOST',
  NO_SIGN: 'NO_SIGN',
  // Decisions
  CONFIRMED: 'CONFIRMED',
  CORRECTED: 'CORRECTED',
  REJECTED: 'REJECTED',
  NEEDS_REPEAT: 'NEEDS_REPEAT',
  ABSTAINED: 'ABSTAINED',
  MARK_INSUFFICIENT: 'MARK_INSUFFICIENT',
  // RAG
  GROUNDED: 'GROUNDED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  NEEDS_TEACHER: 'NEEDS_TEACHER',
  SOURCES_CONFLICT: 'SOURCES_CONFLICT',
  UNKNOWN: 'UNKNOWN',
  REVIEW: 'REVIEW',
  // Knowledge
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  SUPERSEDED: 'SUPERSEDED',
  REVOKED: 'REVOKED',
  ACTIVE: 'ACTIVE',
  // Audio
  AUDIO_REQUESTED: 'AUDIO_REQUESTED',
  AUDIO_STARTED: 'AUDIO_STARTED',
  AUDIO_COMPLETED: 'AUDIO_COMPLETED',
  AUDIO_FAILED: 'AUDIO_FAILED',
  // Storage
  SAVED_LOCALLY: 'SAVED_LOCALLY',
  EXPORTED: 'EXPORTED',
  // Comparison
  IMPROVED: 'IMPROVED',
  STABLE: 'STABLE',
  WORSE: 'WORSE',
  UNCLEAR: 'UNCLEAR',
} as const;
export type StatusLabel = typeof StatusLabel[keyof typeof StatusLabel];
